//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.17
//
package com.amazonaws.mobile;

import com.amazonaws.mobilehelper.config.AWSMobileHelperConfiguration;
import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 225d612b-b3c0-4357-a491-679fe8210f4c aws-my-sample-app-android-v0.17";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:ebaf66a1-6a3d-43cc-942a-27871a793499";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "androidfinal-contentdelivery-mobilehub-1670848087";
    public static final Regions AMAZON_CONTENT_DELIVERY_S3_REGION =
       Regions.fromName("us-east-1");
    public static final String AMAZON_CLOUD_FRONT_DISTRIBUTION_DOMAIN =
        "doij9tvcuporx.cloudfront.net";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_SnITYDdfw";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "6k146t3hdftdvl16uf9ut18v97";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "ch6sr2mu8n2bng38nejhs2qs1majn23j8me3egghks04kdttbdk";

    private static final AWSMobileHelperConfiguration helperConfiguration = new AWSMobileHelperConfiguration.Builder()
        .withCognitoRegion(AMAZON_COGNITO_REGION)
        .withCognitoIdentityPoolId(AMAZON_COGNITO_IDENTITY_POOL_ID)
        .withCognitoUserPool(AMAZON_COGNITO_USER_POOL_ID,
            AMAZON_COGNITO_USER_POOL_CLIENT_ID, AMAZON_COGNITO_USER_POOL_CLIENT_SECRET)
        .build();
    /**
     * @return the configuration for AWSKit.
     */
    public static AWSMobileHelperConfiguration getAWSMobileHelperConfiguration() {
        return helperConfiguration;
    }
}
